name: Build Windows EXE

# 触发条件，定义哪些事件触发工作流
on:
  push:
    branches:
      - main  # 当 push 到 main 分支时触发
  pull_request:
    branches:
      - main  # 当向 main 分支发起 pull request 时触发

jobs:
  build:
    runs-on: windows-latest  # 在 Windows 环境中运行

    steps:
      # 步骤 1: Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤 2: 设置 Python 环境
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      # 步骤 3: 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # 步骤 4: 打包 Python 程序
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py  # 你可以修改为你自己的 Python 脚本文件

      # 步骤 5: 上传构建好的 .exe 文件
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-exe
          path: dist/*.exe  # 指定 PyInstaller 输出的 EXE 文件路径
